### ISSUE TITLE
Chat

### ISSUE THREAD

**Issue by di48l069** [flashwave/railgun#1]
Good day @flashwave 

I really like this application really cool, I my self is busy creating a chat application was wondering can you maybe assist me with your amazing auth functionality you have in railgun?

My application is uses .netcore framework and for now user joins using a name and messages on encrypted on fly using RSA :)

**Comment by flashwave** [comment]
railgun is still very much in development itself too so i'm moving stuff around a lot too, i appreciate the interest and invitation though

the modular dll loading for the auth and protocols is done via this class, https://github.com/flashwave/railgun/blob/master/Railgun.Chat/DllLoader.cs

**Comment by di48l069** [comment]
@flashwave I added you to repro to look around 👍 if you ever want to add ideas please be my guess very simple chat at the moment.

**Comment by flashwave** [comment]
alright, gonna close this issue now then
